theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "⛁"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

#[[block]]
#block = "music"
#player = "spotify"
#buttons = ["play", "next"]

#[[block]]
#block = "net"
#device = "wlp3s0"
#interval = 5
#use_bits = false
#format = "{ssid} {signal_strength} {ip} {speed_down} {graph_down}"

[[block]]
block = "networkmanager"
#on_click = "alacritty -e nmtui"

#[[block]]
#block = "memory"
#display_type = "memory"
#format_mem = "{Mup}%"
#format_swap = "{SUp}%"

[[block]]
block = "memory"
#format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_mem = "{Mup}%"
#format_swap = "{SUm}MB/{STm}MB({SUp}%)"
#display_type = "memory"
#icons = true
#clickable = true
#interval = 5
#warning_mem = 80
#warning_swap = 80
#critical_mem = 95
#critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
#format = "{min}° min, {max}° max, {average}° avg"
format = "{average}° avg"


[[block]]
block = "load"
info = 0.3
warning = 0.6
critical = 0.9
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "time"
interval = 60
#format = "%a %d/%m %R"
format = "%F/%R"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

#[[block]]
#block = "xrandr"
#icons = true
#resolution = true
#interval = 2
